### ISSUE TITLE
Edge-Guided Sampling

### ISSUE THREAD

**Issue by NekonekoHu** [KexianHust/Structure-Guided-Ranking-Loss#10]
thanks for your great work!
how did you achieve Edge-Guided Sampling? what does valid-mask mean?

**Comment by KexianHust** [comment]
For each edge point, we sample 4 points according to the Eqn.5 in the paper. Also, you can find the sampling details in the algorithm 1. The valid masks indicate the pixels whose GT depth values are valid. For those invalid GT, we should ignore their losses during training.
