### ISSUE TITLE
No module named 'models.syncbn.modules.functional._syncbn._ext.syncbn._syncbn'

### ISSUE THREAD

**Issue by volcanoxs** [KexianHust/Structure-Guided-Ranking-Loss#11]
Thanks for your great job.
When I run the demo, there is an error,'No module named 'models.syncbn.modules.functional._syncbn._ext.syncbn._syncbn'
How can I handle this problem?

**Comment by KexianHust** [comment]
Have you compiled the syncbn module in models/syncbn?

**Comment by volcanoxs** [comment]
No.
So,how to compile the syncbn module.
Sorry for asking such a stupid question.

**Comment by jia199903** [comment]
请问具体怎么编译呢
