### ISSUE TITLE
about the paper

### ISSUE THREAD

**Issue by volcanoxs** [KexianHust/Structure-Guided-Ranking-Loss#12]
Hi
Thanks four you great job.
I have read your paper. You have made a lot of experiments.Could you tell me where to download the MC model or its dataset?

**Comment by KexianHust** [comment]
You can find the MC model and dataset via https://mannequin-depth.github.io/

**Comment by volcanoxs** [comment]
Thank you for your answer.
I have an another question.How do you choose the sample number M and N?

**Comment by KexianHust** [comment]
M and N are both image-dependent since each image has a different number of valid ground truth pixels and edge points.

**Comment by volcanoxs** [comment]
Yes.I know that.What is the relationship between M and image?1% or 10% or more?

**Comment by KexianHust** [comment]
The ratio between M and image varies from each image. I think it is more than 10%.
