### ISSUE TITLE
Dataset Available?

### ISSUE THREAD

**Issue by ryanqiutu** [KexianHust/Structure-Guided-Ranking-Loss#16]
Great job!!! But I want to know if the datasets can be available?

**Comment by KexianHust** [comment]
Yes, you can download the dataset via this link: https://drive.google.com/file/d/1OVOx6x-B0Cs-m2z_-7ZxSgRFHz_VBvDd/view?usp=sharing.

**Comment by ryanqiutu** [comment]
Thanks very much. I get the datasets. I've downed twice before via this link: https://drive.google.com/file/d/1OVOx6x-B0Cs-m2z_-7ZxSgRFHz_VBvDd/view, but aborted every time. I've thought maybe you just don't open the datasets. Come on, Huster!!!
