### ISSUE TITLE
Question about ground-truth depth of the dataset

### ISSUE THREAD

**Issue by dzngo** [KexianHust/Structure-Guided-Ranking-Loss#17]
Firstly, thank you for your amazing work!

I have a question about the ground-truth saved in png files. Is this the stereo disparity of left-right image pair?

I'm currently working on stereo depth estimation and your dataset would help me a lot on my project. I'm looking forward to your response!

**Comment by KexianHust** [comment]
Actually, our ground truths are derived from optical flow since there exists vertical disparity in web stereo image pairs. We use the horizontal component of optical flow as disparity.
