### ISSUE TITLE
Output resolution

### ISSUE THREAD

**Issue by dfrumkin** [KexianHust/Structure-Guided-Ranking-Loss#3]
I see that your network has upsample as the last layer, meaning it generates its output at half the input resolution and then you bilinearly upsample it.  Why do you do that?  For example, why not use extra channels to retrieve information at a higher resolution?

**Comment by KexianHust** [comment]
Considering the trade-off between accuracy and computational cost, we did not add additional conv layers at a higher resolution.

**Comment by dfrumkin** [comment]
Thank you for your reply!  I still feel you could easily squeeze extra performance by using a better decoder (e.g. start by removing biases from the convolutions).  But the main points of your work are the ranking loss and the dataset, which are great.  Thank you!

**Comment by KexianHust** [comment]
Thank you for your advice! I agree that a better decoder would further improve the performance, and we are working on it.
